server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER
      
  cloud: # Fix the typo from 'clod' to 'cloud'
    config:
      server:
        git:
          uri: https://github.com/NawazAfi/microservice-config
          clone-on-start: true
